// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Retrospective_EFSQLRetrospectiveDbImpl;

namespace Retrospective_EFSQLRetroSpectiveDbImpl.Migrations
{
    [DbContext(typeof(RetroSpectiveDbContext))]
    partial class RetroSpectiveDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Retrospective_Core.Models.Facilitator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RetrospectiveId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RetrospectiveId");

                    b.ToTable("Facilitators");
                });

            modelBuilder.Entity("Retrospective_Core.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FacilitatorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacilitatorId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Retrospective_Core.Models.RetroCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RetroCards")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RetroCards");

                    b.ToTable("RetroCards");
                });

            modelBuilder.Entity("Retrospective_Core.Models.RetroColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RetroColumns")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RetroColumns");

                    b.ToTable("RetroColumns");
                });

            modelBuilder.Entity("Retrospective_Core.Models.Retrospective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RetroSpectives");
                });

            modelBuilder.Entity("Retrospective_Core.Models.Facilitator", b =>
                {
                    b.HasOne("Retrospective_Core.Models.Retrospective", "Retrospective")
                        .WithMany()
                        .HasForeignKey("RetrospectiveId");
                });

            modelBuilder.Entity("Retrospective_Core.Models.Participant", b =>
                {
                    b.HasOne("Retrospective_Core.Models.Facilitator", null)
                        .WithMany("Participants")
                        .HasForeignKey("FacilitatorId");
                });

            modelBuilder.Entity("Retrospective_Core.Models.RetroCard", b =>
                {
                    b.HasOne("Retrospective_Core.Models.RetroColumn", null)
                        .WithMany("RetroCards")
                        .HasForeignKey("RetroCards");
                });

            modelBuilder.Entity("Retrospective_Core.Models.RetroColumn", b =>
                {
                    b.HasOne("Retrospective_Core.Models.Retrospective", null)
                        .WithMany("RetroColumns")
                        .HasForeignKey("RetroColumns");
                });
#pragma warning restore 612, 618
        }
    }
}
