export const dictionary = {
    // notifications
    'RETROBOARD_CLEAN_ACTION_CONFIRM_NOTI': 'Weet u zeker dat u dit RetroBoard wilt opschonen? (Let op! Kan niet ongedaan gemaakt worden!)',
    'RETROBOARD_CLEAN_ERROR_ALREADY_NOTI': 'Dit RetroBoard is al leeg!',
    'RETROBOARD_EMPTY_COLUMN_NOTI': (title) => `Weet u zeker dat u kolom ${title} wilt leegmaken?`,
    'RETROBOARD_DELETE_COLUMN_NOTI': (title) => `Weet u zeker dat u ${title} wilt verwijderen`,
    'RETROBOARD_DELETE_FAMILY_NOTI': (title) => `Weet u zeker dat u de familie ${title} wilt verwijderen?`,
    'RETROBOARD_DELETE_CARD_NOTI': 'Weet u zeker dat u deze kaart wilt verwijderen?',
    'RETROBOARD_EDIT_FAMILY_NOTI': (title) => `Verander groep ${title} naar:`,
    'RETROBOARD_EDIT_COLUMN_TITLE_NOTI': (title) => `Verander column ${title} naar:`,
    'SNACKBAR_SUCCES_EMPTY': 'Succesvol geleegd',
    'SNACKBAR_SUCCES_DELETE': 'Succesvol verwijderd',
    'SNACKBAR_SUCCESS_ADD': 'Succesvol toegevoegd',
    'SNACKBAR_SUCCES_REGISTERED': 'Succesvol geregistreerd',
    'SNACKBAR_SUCCES_LOGGED_OUT': 'Succesvol uitgelogd',
    'SNACKBAR_SUCCES_LOGGED_IN': 'Succesvol uitgelogd',
    'SNACKBAR_OK': 'OK',
    'HOME_MUST_REGISTER': 'U moet Ingelogd zijn om een Board aan te kunnen maken.',

    // titles
    'WELCOME_TITLE': 'Welkom',
    'CREATE_BOARD_TITLE': 'Nieuw Board',
    'REGISTER_TITLE': 'Registreer',
    'EDIT_TITLE': 'Bewerken',
    'CONFIRMATION_TITLE': 'Confirmatie',
    'LOGIN_TITLE': 'Login',
    'DASHBOARD_TITLE': 'Dashboard',
    'RECOVERY_TITLE': 'Herstellen',

    // forms
    'FILL_IN_NAME_FORM': 'Voer een naam in*',
    'FILL_IN_DESC_OPTIONOL_FORM': 'Voer een beschrijving in (optioneel)',
    'FILL_IN_DESC_FORM': 'Voer een beschrijving in',
    'FILL_IN_TITLE_FORM': 'Voer een titel in',

    // buttons
    'CREATE_NEW_BOARD_BTN': 'Creëer nieuw Board',
    'CREATE_NEW_COLUMN_BTN': 'Voeg een kolom toe',
    'CREATE_NEW_CARD_BTN': 'Voeg een kaart toe',
    'CREATE_NEW_FAMILY_BTN': 'Voeg een groep toe',
    'RETURN_BTN': 'Terug',
    'CANCEL_BTN': 'Annuleer',
    'CREATE_BTN': 'Aanmaken',
    'EDIT_BTN': 'Aanpassen',
    'APPLY_BTN': 'Toepassen',
    'ADD_BTN': 'Voeg toe',
    'EMPTY_COLUMN_BTN': 'Maak kolom leeg',
    'DELETE_COLUMN_BTN': 'Verwijder kolom',
    'EDIT_COLUMN_BTN': 'Bewerk kolomnaam',
    'LOGIN_BTN': 'Log in',
    'LOGOUT_BTN': 'Log out',
    'REGISTER_BTN': 'Registreer',
    'YES_BTN': 'Ja',
    'NO_BTN': 'Nee',

    // errors
    'REQUIRES_NAME_ERROR': 'Naam is <strong>verplicht</strong>',
    'REQUIRES_PASSWORD_ERROR': 'Wachtwoord is <strong>verplicht</strong>',
    'REQUIRES_EMAIL_ERROR': 'Email is <b>verplicht</b>',
    'REQUIRES_FIRSTNAME_ERROR': 'Voornaam is <strong>verplicht</strong>',
    'REQUIRES_LASTNAME_ERROR': 'Achternaam is <strong>verplicht</strong>',
    'REQUIRES': 'Is <strong>verplicht</strong>',
    'FAULTY_NAME_ERROR': 'Deze naam is niet geldig',
    'FAULTY_EMAIL_ERROR': 'Deze email is niet geldig',
    'FAULTY_PASSWORD_ERROR': 'Minimaal acht characters, 1 cijfer, 1 hoofdletter, 1 kleine letter en een speciaal teken!',
    'TEXT_TOO_LONG': 'Deze tekst is te lang',
    'TEXT_TOO_LONG_40': 'Maximaal 40 characters.',
    'TEXT_TOO_LONG_250': 'Maximaal 250 characters.',
    'PASSWORD_MATCH_ERROR': 'Wachtwoorden komen niet overeen!',

    // utils
    'PLACEHOLDER_DRAG': 'Sleep hierheen',
    'PLACEHOLDER_COLUMN_EDIT': 'Groepsnaam',
    'PLACEHOLDER_EMAIL': 'Email',
    'PLACEHOLDER_PASSWORD': 'Wachtwoord',
    'PLACEHOLDER_PASSWORD_REPEAT': 'Herhaal wachtwoord',
    'STATS_COLUMNS': 'Aantal kolommen:',
    'STATS_CARTS': 'Aantal kaarten:',
    'STATS_FAMILIES': 'Aantal groepen:'
};
